// QUOTES
export const QUOTE_LIST_REQUEST = 'QUOTE_LIST_REQUEST';
export const QUOTE_LIST_SUCCESS = 'QUOTE_LIST_SUCCESS';
export const QUOTE_LIST_FAIL = 'QUOTE_LIST_FAIL';

// AUTH
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_INFO_REQUEST = 'USER_UPDATE_INFO_REQUEST';
export const USER_UPDATE_INFO_SUCCESS = 'USER_UPDATE_INFO_SUCCESS';
export const USER_UPDATE_INFO_FAIL = 'USER_UPDATE_INFO_FAIL';
export const USER_UPDATE_INFO_RESET = 'USER_UPDATE_INFO_RESET';

// PROFILES
export const PROFILE_LIST_REQUEST = 'PROFILE_LIST_REQUEST';
export const PROFILE_LIST_SUCCESS = 'PROFILE_LIST_SUCCESS';
export const PROFILE_LIST_FAIL = 'PROFILE_LIST_FAIL';
export const PROFILE_LIST_RESET = 'PROFILE_LIST_RESET';

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';
export const PROFILE_DETAILS_RESET = 'PROFILE_DETAILS_RESET';

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';

export const PROFILE_UPDATE_EXPERIENCES_REQUEST = 'PROFILE_UPDATE_EXPERIENCES_REQUEST';
export const PROFILE_UPDATE_EXPERIENCES_SUCCESS = 'PROFILE_UPDATE_EXPERIENCES_SUCCESS';
export const PROFILE_UPDATE_EXPERIENCES_FAIL = 'PROFILE_UPDATE_EXPERIENCES_FAIL';
export const PROFILE_UPDATE_EXPERIENCES_RESET = 'PROFILE_UPDATE_EXPERIENCES_RESET';

export const PROFILE_UPDATE_PROJECTS_REQUEST = 'PROFILE_UPDATE_PROJECTS_REQUEST';
export const PROFILE_UPDATE_PROJECTS_SUCCESS = 'PROFILE_UPDATE_PROJECTS_SUCCESS';
export const PROFILE_UPDATE_PROJECTS_FAIL = 'PROFILE_UPDATE_PROJECTS_FAIL';
export const PROFILE_UPDATE_PROJECTS_RESET = 'PROFILE_UPDATE_PROJECTS_RESET';

export const PROFILE_LIST_GITHUB_REQUEST = 'PROFILE_LIST_GITHUB_REQUEST';
export const PROFILE_LIST_GITHUB_SUCCESS = 'PROFILE_LIST_GITHUB_SUCCESS';
export const PROFILE_LIST_GITHUB_FAIL = 'PROFILE_LIST_GITHUB_FAIL';
export const PROFILE_LIST_GITHUB_RESET = 'PROFILE_LIST_GITHUB_RESET';

export const PROFILE_LIST_FOLLOWED_REQUEST = 'PROFILE_LIST_FOLLOWED_REQUEST';
export const PROFILE_LIST_FOLLOWED_SUCCESS = 'PROFILE_LIST_FOLLOWED_SUCCESS';
export const PROFILE_LIST_FOLLOWED_FAIL = 'PROFILE_LIST_FOLLOWED_FAIL';

export const PROFILE_UPDATE_FOLLOWS_REQUEST = 'PROFILE_UPDATE_FOLLOWS_REQUEST';
export const PROFILE_UPDATE_FOLLOWS_SUCCESS = 'PROFILE_UPDATE_FOLLOWS_SUCCESS';
export const PROFILE_UPDATE_FOLLOWS_FAIL = 'PROFILE_UPDATE_FOLLOWS_FAIL';

// POST
export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';
export const POST_LIST_RESET = 'POST_LIST_RESET';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';
export const POST_DETAILS_RESET = 'POST_DETAILS_RESET';

export const POST_LIST_OWN_REQUEST = 'POST_LIST_OWN_REQUEST';
export const POST_LIST_OWN_SUCCESS = 'POST_LIST_OWN_SUCCESS';
export const POST_LIST_OWN_FAIL = 'POST_LIST_OWN_FAIL';
export const POST_LIST_OWN_RESET = 'POST_LIST_OWN_RESET';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_UPDATE_LIKES_REQUEST = 'POST_UPDATE_LIKES_REQUEST';
export const POST_UPDATE_LIKES_SUCCESS = 'POST_UPDATE_LIKES_SUCCESS';
export const POST_UPDATE_LIKES_FAIL = 'POST_UPDATE_LIKES_FAIL';

export const POST_UPDATE_FOLLOWS_REQUEST = 'POST_UPDATE_FOLLOWS_REQUEST';
export const POST_UPDATE_FOLLOWS_SUCCESS = 'POST_UPDATE_FOLLOWS_SUCCESS';
export const POST_UPDATE_FOLLOWS_FAIL = 'POST_UPDATE_FOLLOWS_FAIL';

export const POST_CREATE_COMMENT_REQUEST = 'POST_CREATE_COMMENT_REQUEST';
export const POST_CREATE_COMMENT_SUCCESS = 'POST_CREATE_COMMENT_SUCCESS';
export const POST_CREATE_COMMENT_FAIL = 'POST_CREATE_COMMENT_FAIL';
export const POST_CREATE_COMMENT_RESET = 'POST_CREATE_COMMENT_RESET';

export const POST_DELETE_COMMENT_REQUEST = 'POST_DELETE_COMMENT_REQUEST';
export const POST_DELETE_COMMENT_SUCCESS = 'POST_DELETE_COMMENT_SUCCESS';
export const POST_DELETE_COMMENT_FAIL = 'POST_DELETE_COMMENT_FAIL';
export const POST_DELETE_COMMENT_RESET = 'POST_DELETE_COMMENT_RESET';

export const POST_CREATE_REVIEW_REQUEST = 'POST_CREATE_REVIEW_REQUEST';
export const POST_CREATE_REVIEW_SUCCESS = 'POST_CREATE_REVIEW_SUCCESS';
export const POST_CREATE_REVIEW_FAIL = 'POST_CREATE_REVIEW_FAIL';
export const POST_CREATE_REVIEW_RESET = 'POST_CREATE_REVIEW_RESET';

export const POST_DELETE_REVIEW_REQUEST = 'POST_DELETE_REVIEW_REQUEST';
export const POST_DELETE_REVIEW_SUCCESS = 'POST_DELETE_REVIEW_SUCCESS';
export const POST_DELETE_REVIEW_FAIL = 'POST_DELETE_REVIEW_FAIL';
export const POST_DELETE_REVIEW_RESET = 'POST_DELETE_REVIEW_RESET';

export const POST_TOP_REQUEST = 'POST_TOP_REQUEST';
export const POST_TOP_SUCCESS = 'POST_TOP_SUCCESS';
export const POST_TOP_FAIL = 'POST_TOP_FAIL';

export const POST_LATEST_REQUEST = 'POST_LATEST_REQUEST';
export const POST_LATEST_SUCCESS = 'POST_LATEST_SUCCESS';
export const POST_LATEST_FAIL = 'POST_LATEST_FAIL';

export const POST_LIST_LIKED_REQUEST = 'POST_LIST_LIKED_REQUEST';
export const POST_LIST_LIKED_SUCCESS = 'POST_LIST_LIKED_SUCCESS';
export const POST_LIST_LIKED_FAIL = 'POST_LIST_LIKED_FAIL';

export const POST_LIST_FOLLOWED_REQUEST = 'POST_LIST_FOLLOWED_REQUEST';
export const POST_LIST_FOLLOWED_SUCCESS = 'POST_LIST_FOLLOWED_SUCCESS';
export const POST_LIST_FOLLOWED_FAIL = 'POST_LIST_FOLLOWED_FAIL';
