// ERRORS AND ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// QUOTES
export const QUOTE_LIST_REQUEST = 'QUOTE_LIST_REQUEST';
export const QUOTE_LIST_SUCCESS = 'QUOTE_LIST_SUCCESS';
export const QUOTE_LIST_FAIL = 'QUOTE_LIST_FAIL';

// AUTH
export const CREATE_USER = 'CREATE_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_OWN_DETAILS = 'FETCH_OWN_DETAILS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';
export const DESTROY_USER = 'DESTROY_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

// PROFILES
export const FETCH_PROFILE_LIST = 'FETCH_PROFILE_LIST';
export const FETCH_GITHUB_LIST = 'FETCH_GITHUB_LIST';
export const RESET_PROFILE_LIST = 'RESET_POST_LIST';
export const FETCH_PROFILE_FOLLOWERS = 'FETCH_PROFILE_FOLLOWERS';

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const DESTROY_PROFILE = 'DESTROY_PROFILE';
export const FETCH_PROFILE_DETAILS = 'FETCH_PROFILE_DETAILS';
export const RESET_PROFILE_DETAILS = 'RESET_PROFILE_DETAILS';

export const UPDATE_PROFILE_FOLLOWS = 'UPDATE_PROFILE_FOLLOWS';
export const UPDATE_FAIL_PROFILE_FOLLOWS = 'UPDATE_FAIL_PROFILE_FOLLOWS';

export const UPDATE_PROFILE_EXPERIENCE = 'UPDATE_PROFILE_EXPERIENCE';
export const UPDATE_FAIL_PROFILE_EXPERIENCE = 'UPDATE_FAIL_PROFILE_EXPERIENCE';

export const UPDATE_PROFILE_PROJECT = 'UPDATE_PROFILE_PROJECT';
export const UPDATE_FAIL_PROFILE_PROJECT = 'UPDATE_FAIL_PROFILE_PROJECT';

export const ERROR_FETCH_GITHUB = 'ERROR_FETCH_GITHUB';

// POST
export const FETCH_POST_LIST = 'FETCH_POST_LIST';
export const FETCH_FOLLOWED_POSTS = 'FETCH_FOLLOWED_POSTS';
export const FETCH_LIKED_POSTS = 'FETCH_LIKED_POSTS';
export const FETCH_LATEST_POSTS = 'FETCH_LATEST_POSTS';
export const FETCH_TOP_POSTS = 'FETCH_TOP_POSTS';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const RESET_POST_LIST = 'RESET_POST_LIST';

export const CREATE_POST = 'CREATE_POST';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const RESET_POST_DETAILS = 'RESET_POST_DETAILS';

export const UPDATE_POST_LIKES = 'UPDATE_POST_LIKES';
export const UPDATE_FAIL_POST_LIKES = 'UPDATE_FAIL_POST_LIKES';

export const UPDATE_POST_FOLLOWS = 'UPDATE_POST_FOLLOWS';
export const UPDATE_FAIL_POST_FOLLOWS = 'UPDATE_FAIL_POST_FOLLOWS';

export const DESTROY_POST = 'DESTROY_POST';
export const DESTROY_FAIL_POST = 'DESTROY_FAIL_POST';

export const CREATE_POST_COMMENT = 'CREATE_POST_COMMENT';
export const CREATE_POST_COMMENT_FAIL = 'CREATE_POST_COMMENT_FAIL';
export const DESTROY_POST_COMMENT = 'DESTROY_POST_COMMENT';
export const DESTROY_FAIL_POST_COMMENT = 'DESTROY_FAIL_POST_COMMENT';

export const CREATE_POST_REVIEW = 'CREATE_POST_REVIEW';
export const CREATE_POST_REVIEW_FAIL = 'CREATE_POST_REVIEW_FAIL';
export const DESTROY_POST_REVIEW = 'DESTROY_POST_REVIEW';
export const DESTROY_FAIL_POST_REVIEW = 'DESTROY_FAIL_POST_REVIEW';

// MODAL PSEUDO CONSTANTS
export const MODAL_LIKED_POSTS = 'MODAL_LIKED_POSTS';
export const MODAL_USER_POSTS = 'MODAL_USER_POSTS';
export const MODAL_FOLLOWED_POSTS = 'MODAL_FOLLOWED_POSTS';
export const MODAL_TOP_POSTS = 'MODAL_TOP_POSTS';
export const MODAL_FOLLOWED_PROFILES = 'MODAL_FOLLOWED_PROFILES';
