// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// AUTH
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

// PROFILES
export const PROFILE_LIST_REQUEST = 'PROFILE_LIST_REQUEST';
export const PROFILE_LIST_SUCCESS = 'PROFILE_LIST_SUCCESS';
export const PROFILE_LIST_FAIL = 'PROFILE_LIST_FAIL';

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';
export const PROFILE_CREATE_RESET = 'PROFILE_CREATE_RESET';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';

export const PROFILE_LIST_GITHUB_REQUEST = 'PROFILE_LIST_GITHUB_REQUEST';
export const PROFILE_LIST_GITHUB_SUCCESS = 'PROFILE_LIST_GITHUB_SUCCESS';
export const PROFILE_LIST_GITHUB_FAIL = 'PROFILE_LIST_GITHUB_FAIL';

export const PROFILE_LIST_FOLLOWS_REQUEST = 'PROFILE_LIST_FOLLOWS_REQUEST';
export const PROFILE_LIST_FOLLOWS_SUCCESS = 'PROFILE_LIST_FOLLOWS_SUCCESS';
export const PROFILE_LIST_FOLLOWS_FAIL = 'PROFILE_LIST_FOLLOWS_FAIL';

export const PROFILE_UPDATE_FOLLOWS_REQUEST = 'PROFILE_UPDATE_FOLLOWS_REQUEST';
export const PROFILE_UPDATE_FOLLOWS_SUCCESS = 'PROFILE_UPDATE_FOLLOWS_SUCCESS';
export const PROFILE_UPDATE_FOLLOWS_FAIL = 'PROFILE_UPDATE_FOLLOWS_FAIL';

// POST
export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_UPDATE_LIKES_REQUEST = 'POST_UPDATE_LIKES_REQUEST';
export const POST_UPDATE_LIKES_SUCCESS = 'POST_UPDATE_LIKES_SUCCESS';
export const POST_UPDATE_LIKES_FAIL = 'POST_UPDATE_LIKES_FAIL';

export const POST_UPDATE_FOLLOWS_REQUEST = 'POST_UPDATE_FOLLOWS_REQUEST';
export const POST_UPDATE_FOLLOWS_SUCCESS = 'POST_UPDATE_FOLLOWS_SUCCESS';
export const POST_UPDATE_FOLLOWS_FAIL = 'POST_UPDATE_FOLLOWS_FAIL';

export const POST_CREATE_COMMENT_REQUEST = 'POST_CREATE_COMMENT_REQUEST';
export const POST_CREATE_COMMENT_SUCCESS = 'POST_CREATE_COMMENT_SUCCESS';
export const POST_CREATE_COMMENT_FAIL = 'POST_CREATE_COMMENT_FAIL';
export const POST_CREATE_COMMENT_RESET = 'POST_CREATE_COMMENT_RESET';

export const POST_CREATE_REVIEW_REQUEST = 'POST_CREATE_REVIEW_REQUEST';
export const POST_CREATE_REVIEW_SUCCESS = 'POST_CREATE_REVIEW_SUCCESS';
export const POST_CREATE_REVIEW_FAIL = 'POST_CREATE_REVIEW_FAIL';
export const POST_CREATE_REVIEW_RESET = 'POST_CREATE_REVIEW_RESET';

// PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const GET_FOLLOWED_PROFILES = 'GET_FOLLOWED_PROFILES';
export const FOLLOW_PROFILE = 'FOLLOW_PROFILE';
export const UNFOLLOW_PROFILE = 'UNFOLLOW_PROFILE';

// POST
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_FOLLOWS = 'UPDATE_FOLLOWS';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
